project/models.py
from project import db

class Snakes(db.Model):
    __tablename__ = "snakes"

    id = db.Column(db.Integer, primary_key=True)
    species = db.Column(db.String)
    geo_name = db.Column(db.String)
    pic_url = db.Column(db.String)
    find = db.relationship('Finds', backref="snakes")

    def __init__(self, species, geo_name, pic_url):
        self.species = species
        self.geo_name = geo_name
        self.pic_url = pic_url

class Finds(db.Model):
    __tablename__ = "finds"
    id = db.Column(db.Integer, primary_key=True)
    species_id = db.Column(db.Integer, db.ForeignKey('snakes.id'))
    location = db.Column(db.String)
    date = db.Column(db.DATE)
    pic = db.Column(db.String)

    def __init__(self, species_id, location, date, pic):
        self.species_id = species_id
        self.location = location
        self.date = date
        self.pic = pic

project/finds/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, FileField
from wtforms.fields.html5 import DateField

class AddFind(FlaskForm):
    species_id = IntegerField('შეიყვანეთ სახეობის უნიკალური იდენტიფიკატორი:')
    location = StringField('შეიყვანეთ პოვნის ლოკაცია:')
    date = DateField('შეიყვანეთ პოვნის თარიღი:')
    pic = FileField('ფოტო:')
    submit = SubmitField('ატვირთვა')


class DelFind(FlaskForm):
    id = IntegerField('')
    submit = SubmitField('წაშლა')

project/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = 'SECRET'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

from project.finds.views import finds_blueprint
from project.snakes.views import snakes_blueprint

app.register_blueprint(finds_blueprint, url_prefix='/finds' )
app.register_blueprint(snakes_blueprint, url_prefix='/snakes')

project/finds/views.py
from flask import render_template, redirect, url_for, Blueprint, request
from project import db
from project.models import Finds, Snakes
from project.finds.forms import AddFind
from werkzeug.utils import secure_filename
import os

finds_blueprint = Blueprint('finds',
                              __name__,
                              template_folder='templates/finds')

@finds_blueprint.route('/add', methods=['GET', 'POST'])
def add_find():
    form = AddFind()
    if form.validate_on_submit():
        species_id = form.species_id.data
        location = form.location.data
        date = form.date.data
        filename = secure_filename(form.pic.data.filename)
        new_find = Finds(species_id, location, date, filename)
        db.session.add(new_find)
        db.session.commit()

        file_path = f"project/static/{filename}"
        dirname = os.path.dirname(file_path)
        if not os.path.exists(dirname):
            os.makedirs(dirname)

        form.pic.data.save(file_path)


        return redirect(url_for('finds.thanks'))
    return render_template('add_find.html', form=form)

@finds_blueprint.route('/thanks')
def thanks():
    return render_template('thanks.html')


@finds_blueprint.route('/findslist')
def finds_list():
    finds = Finds.query.all()
    return render_template('finds_list.html', finds=finds)

@finds_blueprint.route('/species/<id>')
def find_id(id):
    snake = Snakes.query.filter_by(id=id)
    finds = Finds.query.filter_by(species_id=id)
    return render_template('find_id.html', finds=finds, snake=snake)

project/snakes/views.py
from flask import render_template, Blueprint
from project.models import Finds, Snakes

snakes_blueprint = Blueprint('snakes',
                              __name__,
                              template_folder='templates/snakes')

@snakes_blueprint.route('/snakelist')
def snake_list():
    snakes = Snakes.query.all()
    return render_template('snake_list.html', snakes=snakes)




@snakes_blueprint.route('/viperidae')
def viperidae():
    return render_template('viperidae.html')

@snakes_blueprint.route('/colubridae')
def colubridae():
    return render_template('colubridae.html')

@snakes_blueprint.route('/typhlopidae')
def typhlopidae():
    return render_template('typhlopidae.html')

@snakes_blueprint.route('/boidae')
def boidae():
    return render_template('boidae.html')

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>გველები</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>

<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">

      <a class="navbar-brand" href="{{ url_for('home') }}">
    <img src="{{ url_for('static', filename='logo.png') }}" width="50" height="55" alt="">
        </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('home') }}">მთავარი გვერდი</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('finds.add_find') }}">მონაცემის ატვირთვა</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('finds.finds_list') }}">ბაზა

<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('snakes.snake_list') }}">საქართველოს გველები<span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="რამე გველი" aria-label="Search" style="font-style:italic" >
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">დაგველე</button>
    </form>
  </div>
</nav>
    </div>


    {% block content %}
    {% endblock %}

</body>
</html>

project/templates/home.html
{% extends "base.html" %}
{% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <div class="container">
  <ol class="carousel-indicators" >
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="../static/M_lebetina.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <a href="{{ url_for('snakes.viperidae') }}">
          <h4 style="color: white">გველგესლასებრნი - Viperidae</h4>
        </a>
      </div>
    </div>
    <div class="carousel-item">
      <img src="../static/T_fallax.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <a href="{{ url_for('snakes.colubridae') }}">
          <h4 style="color: white">მცურავები - Colubridae</h4>
        </a>
      </div>
    </div>
    <div class="carousel-item">
      <img src="../static/X_vermicularis.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <a href="{{ url_for('snakes.typhlopidae') }}">
          <h4 style="color: white">გველბრუცასებრნი - Typhlopidae</h4>
        </a>
      </div>
    </div>

    <div class="carousel-item">
        <img src="../static/E_jaculus.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
        <a href="{{ url_for('snakes.boidae') }}">
          <h4 style="color: white">მახრჩობელები - Boidae</h4>
        </a>
      </div>
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev" style="width: 40%;">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next" style="width: 40%;">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
</div>


{% endblock %}

project/templates/snake_list.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 50px;padding: 40px;">
    <h3 align="center">საქართველოს გველები</h3>

    <table class="table" style="border: solid lightgray">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">სახეობა</th>
            <th scope="col">ლათინური სახელი</th>
          </tr>
        </thead>
        <tbody>

            {% for snake in snakes %}
            <tr >
            <th scope="row"><a class="btn btn-light" href="{{ url_for('species_id', id=snake.id) }}" role="button">{{ snake.id }}</a></th>
            <td> {{ snake.geo_name }}</td>
            <td> {{ snake.species }}</td>
        </tr>
            {% endfor %}

        </tbody>
      </table>
</div>
{% endblock %}

project/templates/species_id.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="margin-top: 50px;padding: 40px;">
    <h3 align="center">es gamoasworet</h3>

    <table class="table" style="border: solid lightgray">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">სახეობის ID</th>
            <th scope="col">ლოკაცია</th>
            <th scope="col">თარიღი</th>
            <th scope="col">ფოტო</th>
          </tr>
        </thead>
        <tbody>

            {% for snake in finds %}
            <tr>
            <th scope="row">{{ snake.id }}</th>
            <td> {{ snake.species_id }}</td>
            <td> {{ snake.location }}</td>
            <td> {{ snake.date }}</td>
            <td> <img src="snake.pic"> </td>
        </tr>
            {% endfor %}

        </tbody>
      </table>
</div>
{% endblock %}

project/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron" align="center">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="../static/snek.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">მადლობა!</h5>
    <p class="card-text">თქვენი წვლილი მეცნიერებაში შეტანილია!</p>
    <a href="{{ url_for('home') }}" class="btn btn-primary">მთავარ გვერდზე დაბრუნება</a>
  </div>
</div>
</div>
{% endblock %}